### PR TITLE
Expand code reviews section

### PR DESCRIPTION
**Pull request by joshwlambert**
This PR addresses #41. 

It extends the Code reviews section of blueprints to include reference to the [Tidyteam code review principles](https://code-review.tidyverse.org/), adds explicit points of similarity between Tidyteam and Epiverse-TRACE review practises, and some extra information to aid both Epiverse-TRACE developers or community members how to engage in code reviews.

The text introduced in this PR has caused the Code reviews section to become the largest in the General principles page. I do not have a strong preference as to whether we keep this new information in it's current section or more the new text to a new page in blueprints. This new page might be a good catalyst to work on [Policies around Issues/PRs](https://github.com/epiverse-trace/blueprints/issues/21).

### CODE REVIEW

**Comment by Bisaloo** [comment]
My initial idea was to keep the "general principles" pages short and very high-level and detail ideas in separate pages. But I'm not unsure of what's the best approach :thinking:.

@avallecam @annacarnegie, do you have any recommendations in terms of format?

**Comment by avallecam** [comment]
Grate addition on code reviews, @joshwlambert. @Bisaloo I agree with the idea to keep the "general" short and extend on detailed points in a separate page, similar to the "standards for branching"

**Comment by avallecam** [comment]
It looks good to me, thanks for working on it!

**Review by Bisaloo — APPROVED** [review]
Sounds very good to me! Thanks for contributing! This is ready to go as far as I'm concerned.

Next item on this page would be to address Seb's question in https://github.com/epiverse-trace/blueprints/issues/21: who merges the PR? The author or the reviewer? My personal preference is reviewers approve and author merges but we could present this question to the group.

**Pull request merged**
