### PR TITLE
Start chapter on contribution process

### LINKED ISSUE #6: Policy around git branching & merging process
The goal of this discussion is to settle on a set of common practices around branches & merges in git/GitHub.

# New changes in branches

All changes should be done in branches and submitted by pull requests. Even in simple cases, where a review doesn't seem strictly necessary, using pull requests helps the rest of the team to notice the change and to stay up-to-date on the codebase.

**- Should we enforce this by protecting the `main` branch?**

At the same time, each pull request should focus on a single feature. Pull requests modifying multiple aspects of the code or fixing multiple unrelated bugs are usually more difficult and thus longer to review, which doesn't align well with our agile development method.

Pull requests should target the `main` branch. We do not believe it is necessary to have an intermediate `develop` branch. Because we follow an agile strategy, the stable version on the package corresponds to the latest CRAN release and the development version is the GitHub version.

However, we discourage using branches targeting other branches as this can quickly escalate in difficult to manage conflicts. If you need to add or propose changes to a non-`main` branch, you should either use the [commit suggestions feature from GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request). In more complex cases, you should agree with the person who opened the pull request to push directly to their branches.

# Merge mechanism

GitHub currently has [3 pull request merge mechanisms](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github):

- "Create a merge commit"
- "Squash and merge"
- "Rebase and merge"

The merge commit option is the only option that doesn't rewrite history. As such, it is the preferred option when multiple people commit directly to the same branch without prior concertation.

However, merge commits present other drawbacks, such as creating a heavily non-linear history, which is extremely difficult to read without a client displaying the various branches over time. Notably, it is very difficult to browse & understand a git history with merge commits in GitHub web interface.
For related reasons, merge commits can create flat out unintelligible diffs in pull requests in some cases.

The preference of squash vs simple rebase depends on the quality of the commits in the branches to merge. If the commits are grouped logically, with clear commit messages, they can be rebased & merged directly. If not, then a squash & merge should be preferred.

**- Should we remove the options we choose to not use from the list of options offered by GitHub?**

**- Should we encourage contributors to clean & reorganise their git commit history before merging their branches? [This blog post](https://github.blog/2022-06-30-write-better-commits-build-better-projects/) is a detailed explanation of why this can be beneficial but it is important to note that this is not also straightforward as reorganising commits can easily create conflicts if not done with care.** 

It is also important to note that our choice here also impacts how we should resolve diverging histories locally because the various methods are partially incompatible. For example, it is not possible to rebase & merge a branch that already contains a merge commit. Therefore, if we wish to use "Rebase & merge", we must ensure that collaborators do not create merge commits in their branches.

## Avoiding merge commit when pulling

One common source of unintended merge commits is running `git pull` to fetch remote commits when you already have unpushed local commits. A simple way to solve this is to run `git pull --rebase` instead of just `git pull`. This setting can also be adjusted globally with the following command:

```sh
git config --global pull.rebase true
```

## Future option: merge queues

GitHub has released a 4th merge mechanism (currently in private beta): [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).

This is meant to address one major issue that agile projects encounter. If your project has multiple concurrent pull requests, as soon as you merge one of them, checks in the others become out of date because they ran against an outdated version of the `main` branch. Merge queues solve this issue by creating a queue with all the pull requests you want to merge and running checks against a temporary branch containing all the changes in the queue.

This is likely the mechanism we will want to use in the future but it is currently in beta and detailed documentation is lacking.

### PR DESCRIPTION
**Pull request by Bisaloo**
Scope: this chapter only focuses on the branching/PR/review steps of the contribution process.

Fix #6

### CODE REVIEW

**Comment by Bisaloo** [comment]
The pre-rendered HTML and PDF files are [here](https://github.com/epiverse-trace/blueprints/suites/8815366898/artifacts/401231643).

**Comment by Bisaloo** [comment]
@epiverse-trace/lac @epiverse-trace/lshtm-mrcg, this is ready for review.

If you don't want to read a markdown file, you can get the rendered PDF or HTML version [here](https://github.com/epiverse-trace/blueprints/suites/8815366898/artifacts/401231643).

Any comment is welcome, and [commit suggestions are even better](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews)! Thanks :pray:

**Review by juan-umana — APPROVED** [review]
Hi! There is a problem generating the HTML or PDF file (_Failed to generate URL to download artifact_) so I check the files on GitHub. I found very clear the contribution process, great document! I notice that there are no expected times of response or reviewing, I know is difficult to ensure that but I was wondering if it is something important fo the collaborators

**Review by mauricio110785 — APPROVED** [review]
I found the document pretty self-explanatory which is great. my only concern is that in the document is mentioned that: "we will merge branches fast", and " we will resolve to pull request ASAP" but it is not clear to me who is we. The package maintainer is data.org so it would be good to specifically assign roles.

**Review by GeraldineGomez — APPROVED** [review]
The document is very clear about the contribution process and branch management. Weekly automatic reminders could be included for the review of open PRs. In case there are some dependent PRs or issues, what process would be recommended? maybe it would be appropriate to temporarily create an integrating branch with the changes?

**Review by ntorresd — APPROVED** [review]

**Review by davidsantiagoquevedo — APPROVED** [review]

**Comment by sbfnk** [comment]
It might be good to merge this to prevent it from becoming stale and making contributions/changes from others easier. Seems like we need one more approving review from @jpavlich or @megamezl?

**Comment by Bisaloo** [comment]
I think this needs edits following the discussion we had with LSHTM. I will discuss it tomorrow with the LAC members present at the all-RSEs meeting

**Pull request closed without merging**
